application:
  data-dir: ${DATA_DIR:images}
server.port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/holasend?serverTimesone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 300KB
      max-request-size: 300KB
springdoc:
  swagger-ui:
    path: /swagger-ui.html